# Generated by Django 5.2.2 on 2025-06-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('start', models.DateTimeField(verbose_name='Початок')),
                ('end', models.DateTimeField(verbose_name='Кінець')),
                ('event_type', models.CharField(choices=[('meeting', 'Зустріч'), ('presentation', 'Презентація'), ('training', 'Тренінг'), ('dinner', 'Вечеря'), ('other', 'Інше')], default='meeting', max_length=20, verbose_name='Тип події')),
                ('price', models.IntegerField(default=0)),
                ('payed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['start'],
            },
        ),
    ]
