# Generated by Django 5.2.2 on 2025-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='performed',
            field=models.BooleanField(default=False),
        ),
    ]
