# Generated by Django 5.2.2 on 2025-07-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testter', '0002_event_performed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пo-батькові')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Електронна пошта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефону')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компанія')),
                ('how_payed', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('first_contact', models.DateTimeField(auto_now_add=True, verbose_name='Перший контакт')),
                ('last_contact', models.DateTimeField(auto_now=True, verbose_name='Останній контакт')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('events', models.ManyToManyField(related_name='participants', to='testter.event', verbose_name='Події за участю')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Власник клієнта')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['last_name'],
            },
        ),
    ]
