# Generated by Django 5.2.2 on 2025-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testter', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='events', to='testter.client', verbose_name='Клієнти (якщо є)'),
        ),
    ]
