# Generated by Django 5.2.2 on 2025-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testter', '0004_remove_client_events_event_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='testter.client', verbose_name='Клієнти (якщо є)'),
        ),
    ]
