# Generated by Django 5.2.2 on 2025-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testter', '0005_alter_event_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='events', to='testter.client', verbose_name='Клієнти (якщо є)'),
        ),
    ]
